site/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
//home
get('/',['as'=>'home','uses'=>'StaticPagesController@indexHome']);
//user pages
get('/pages/{slug}',['as'=>'user_pages','uses'=>'StaticPagesController@indexUserPages']);
//about
get('/about',['as'=>'about','uses'=>'StaticPagesController@indexAbout']);
//working conditions
get('/rules',['as'=>'rules','uses'=>'StaticPagesController@indexRules']);
//contacts
//get('/contacts',['as'=>'contacts','uses'=>'StaticPagesController@indexContacts']);
//regions
get('/regions',['as'=>'regions','uses'=>'StaticPagesController@indexRegions']);

get('/data_exchange',['as'=>'data_exchange','uses'=>'DataExchangeController@dataExchange']);
//dataExchange
get('/load_orders',['as'=>'data_exchange','uses'=>'DataExchangeController@LoadOrders']);



//GetCartridgePrice
get('/price/{slug}/{pagination?}',['as'=>'price_brand','uses'=>'CartridgePriceController@getCartidgePrices']);
//DownloadCartridgePrice
get('/exel/{slug?}',['as'=>'exel_download','uses'=>'CartridgePriceController@downloadPriceExel']);



//request
//get('/request',['as'=>'request','uses'=>'RequestController@index']);
//store request
post('/store_request',['as'=>'store_request','uses'=>'RequestController@store_request']);
//store request call back
post('/call_back',['as'=>'call_back','uses'=>'RequestController@call_back']);


//news
get('/news',['as'=>'news','uses'=>'NewsController@index']);
//newsitem
get('/news/{_news_slug}',['as'=>'newsitem','uses'=>'NewsController@indexNewsItem']);

//


//questions
//get('/questions',['as'=>'questions','uses'=>'QuestionsController@index']);
//store questions
//get('/questions_store',['as'=>'store_questions','uses'=>'QuestionsController@store']);

//cart
get('/cart',['as'=>'cart','uses'=>'CartController@index']);
//cart update
post('/cart_update',['as'=>'cart_add','uses'=>'CartController@cart_update']);
//cart order delete
post('/cart_item_delete',['as'=>'cart_item_delete','uses'=>'CartController@cart_item_delete']);
//clean session orders
get('/clean_cart',['as'=>'clean_cart','uses'=>'CartController@clean_cart']);
//add to orders
post('/cart_item_delete',['as'=>'cart_item_delete','uses'=>'CartController@cart_item_delete']);
//save order
post('/save_order',['as'=>'save_order','uses'=>'CartController@save_order']);


//search
get('/search',['as'=>'search','uses'=>'SearchController@search']);
get('/autocomplete',['as'=>'autocomplete','uses'=>'SearchController@autocomplete']);

Route::group(['prefix'=>'uploader','nocsrf' => true],function(){
    Route::match(['get','post'],'/','Fileuploader@upload');
});

site/app/Models/BrandPicture.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use SmartModel\SmartModel;

class BrandPicture extends SmartModel
{
    public static $files = array(
        'image' => array(
            'sizes' => array(
                'list' => array(
                    'size' => '90x70',
                    'process' => 'fitOut',
                ),
            ),
        )
    );

    public function getImageUrlAttribute()
    {
        $this->loadFiles();
        if (count($this->image['sizes']['list']['link'])){
            return asset($this->image['sizes']['list']['link']);
        }
        return asset('img/brands/01.png');
    }

    public function getImageLinkAttribute()
    {
        $this->loadFiles();
        if (count($this->image['sizes']['list']['link'])){
            return asset($this->image['link']);
        }
        return asset('img/brands/01.png');
    }
}

site/app/Models/News.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use SmartModel\SmartModel;

class News extends SmartModel

{
    protected $news_tag_ids = [];
    protected $appends = ['tags_as_string',];

    public $rules = array(
        'title' => 'required',
//        '_slug' => 'required',
    );

    public static $files = array(
        'image' => array(
            'sizes' => array(
                'list' => array(
                    'size' => '161x108',
                    'process' => 'fitOut',
                ),
            ),
        ),
        'image_poster' => array(
            'sizes' => array(
                'poster'=>array(
                    'size' => '408x330',
                    'process' => 'fitOut',
                ),
            ),
        ),
        'og_image' => array(
            'name' => 'native',
        ),
    );

    public  function getTagsAsStringAttribute(){
        $id_news    =   $this->id;
        return (implode(",",\DB::table('tags')
                            ->select('title')
                            ->whereIn('tags.id', \DB::table('tags_to_news')
                                                ->select('id_tag')
                                                ->where('id_news',$id_news)->lists('id_tag'))
                            ->lists('title') ));
    }

    public  function getDateAttribute(){
        return Carbon::parse($this->created_at)->format('d.m.Y');
    }
    
    public  function getImageUrlAttribute(){
        $this->loadFiles();
        if (count($this->image['sizes']['list']['link'])){
            return asset($this->image['sizes']['list']['link']);
        }
        return asset('img/products/01.png');
    }

    public  function getBigImgAttribute(){
        $this->loadFiles();
        if (count($this->image_poster['sizes']['poster']['link'])){
            return asset($this->image_poster['sizes']['poster']['link']);
        }
        return asset('img/image.png');
    }



    public function afterSave() {
        parent::afterSave();
        $id_news = $this->id;
        $id_tags_for_news =  $this->news_tag_ids;
        \DB::table('tags_to_news')->where('id_news',$id_news)->delete();
        $tags_this_news=[];
        foreach($id_tags_for_news as $val){
            $tags_this_news[]=['id_news' =>  $id_news,
                                'id_tag'  =>  $val];
        }
//        dd($tags_this_news);
        \DB::table('tags_to_news')->insert($tags_this_news);

    }

    public  function setTagsAsStringAttribute($val){
        $tags_this_news =  explode(',', $val);
        foreach ($tags_this_news as &$_tag) {
            $_tag = trim($_tag);
        }

        $existing_tags   =    \DB::table('tags')->whereIn('title',$tags_this_news)->lists('title','id');
        $id_existing_tags   =   array_keys($existing_tags);
        $tile_existing_tags =   array_values($existing_tags);
//get tags that still do not have
        $non_existent_tags  =   array_diff( $tags_this_news, $tile_existing_tags);
//form a list of the id record
        $id_tags_for_news  = $id_existing_tags;
//add new tag
        foreach($non_existent_tags as $tag){
            $id_tags_for_news[] = \DB::table('tags')->insertGetId(['title'=>$tag]);
        }
//remove all tags for this news
//        \DB::table('tags_to_news')->where('id_news',$id_news)->delete();

////        $tags_this_news=[];
//        foreach($id_tags_for_news as $val){
//            $tags_this_news[]=['id_news' =>  $id_news,
//                              'id_tag'  =>  $val];
//        }
        $this->news_tag_ids = $id_tags_for_news;
//        write new tags for news

//        \DB::table('tags_to_news')->insert($tags_this_news);
    }

    public static function getNewNews() {
        return \DB::table('news')
            ->where('is_active','=',1)->whereNotNull('_slug')->where('_slug','<>','')
            ->limit(3)->orderBy('created_at','desc')->get();
    }

    public static function getNewsPaginationList($on_page = 10)
    {
        $news = News::where('is_active','=',1)->whereNotNull('_slug')->where('_slug','<>','')
                ->orderBy('created_at','desc')
                ->paginate($on_page);

        return $news;
    }

    public static function getNewsByIds($ids)
    {
        $news = News::where('is_active','=',1)->whereNotNull('_slug')->where('_slug','<>','')
                ->whereIn('id',$ids)
                ->orderBy('created_at','desc')
                ->get();

        return $news;
    }

    public static function getLikeNews($id_news)
    {
        $news_top = \DB::table('tags_to_news')
            ->select(\DB::raw('count(*) as count, id_news'))
            ->join('news', 'id_news', '=', 'news.id')
            ->where('is_active','=',1)->whereNotNull('_slug')->where('_slug','<>','')
            ->whereIn('id_tag',\DB::table('tags_to_news')
                ->where('id_news',$id_news)->lists('id_tag'))
            ->groupBy('id_news')
            ->orderBy('count','desc')
            ->limit(5)->get();

        $news_ids = [];
        foreach ($news_top as $nt) {
            if ($nt->id_news != $id_news) {
                $news_ids[] = $nt->id_news;
            }
        }

        return self::getNewsByIds($news_ids);
//
//        return \DB::table('tags_to_news')
//            ->select(\DB::raw('count(*) as count, id_news, news.title, news.content,news.preview, news.created_at,news.id'))
//            ->join('news', 'id_news', '=', 'news.id')
//            ->where('is_active','=',1)
//            ->whereIn('id_tag',\DB::table('tags_to_news')
//                ->where('id_news',$id_news)->lists('id_tag'))
//            ->groupBy('id_news')
//            ->orderBy('count','desc')
//            ->limit(5)->get();
    }
}

site/resources/views/pages/home_components/mainbrands.blade.php
<div class="mainbrands">
    <div class='container'>
        <div class="mainbrands__title title_1">Скупаем картриджи <br />следующих брендов</div>
        <div class="mainbrands-row">

        @if(count($brands_picture))
                @foreach($brands_picture as $brand)
                    <div class="mainbrands-item greyimg">
                            <a href="{{route('price_brand',$brand->slug)}}"><img src="{{ $brand->image_link}}" alt="" /></a>
                    </div>
                @endforeach
            @endif
        </div>
    </div>
</div>

site/resources/views/pages/home_components/mainformblock.blade.php
<div class="mainformblock">
    <div class='container'>
        <div class="mainformblock-block">
            <div class="mainformblock-block-cell">
                <div class="mainformblock-form">
                    @if(!empty(Session::get('send')) && Session::get('send'))
                        <div class="mainformblock-form__title title_2 title_success">Ваша заявка № {{Session::get('code')}} от {{Session::get('date')}} успешно отправлена</div>
                    @else
                        <div class="mainformblock-form__title title_2">запрос на оценку и продажу<br />картриджей</div>
                    @endif
                    <form action="{{route('store_request')}}" method="post" enctype="multipart/form-data">
{{--                        <input type="hidden" name="recaptcha_response" id="recaptchaResponse">--}}
                        {{ HiddenCaptcha::render() }}
                        <div class="popup-body-row row">
                            <div class="popup-body-column">
                                <input type="text" name="name" data-value="Как к Вам обращаться?" class="popup-body__input" />
                            </div>
                            <div class="popup-body-column">
                                <input type="text" name="phone" data-value="Контактный телефон" placeholder="Контактный телефон" class="popup-body__input" />
                            </div>
                        </div>
                        <div class="popup-body-row row">
                            <div class="popup-body-column">
                                <input type="text" name="email" data-value="Электронная почта" class="popup-body__input req email" />
                            </div>
                            <div class="popup-body-column">
                                <div class="select content-filter__select">
                                    <div class="select-title">
                                        <div class="select-title__arrow"></div>
                                        <div class="select-title__value">Екатеринбург</div>
                                    </div>
                                    <div class="select-options">
                                        <div class="select-options-inside">
                                            <div class="select-options__value">Екатеринбург</div>
                                            <div class="select-options__value">Свердловская область и Урал</div>
                                            <div class="select-options__value">Другой город</div>
                                        </div>
                                        <input type="hidden" class="req" name="place" value="Екатеринбург">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="popup-body-row">
                            <textarea name="mess" data-value="Комментарии к заявке" class="popup-body__input"></textarea>
                        </div>
                        <div class="popup-body-row row">
                            <div class="popup-body-column-recaptcha">
                                <div id="g-recaptcha"></div>
                            </div>
                        </div>
                        <div class="popup-body-row row">
                            <div class="popup-body-column">
                                <div class="popup-body__file">
                                    <span>Загрузить фотографии</span>
                                </div>
                                <input type="file" name="images[]" class="popup-body__hiddenfile" multiple/>
                            </div>
                            <div class="popup-body-column">
                                <input type="hidden" data-value="quick_request"  name="type"/>
                                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                <button type="submit" formaction="{{route('store_request')}}" @if(!env('TEST_SITE', false)) onclick="yaCounter38574200.reachGoal('GLAVFORMOTPR')" @endif class="popup-body__btn"><span>Отправить заявку</span></button>
                            </div>
                        </div>
                        <div class="popup-body-row last">
                            {{--<div class="popup-body-req">--}}
                                {{--<span class="star">*</span> Обязательные поля--}}
                            {{--</div>--}}
                        </div>
                    </form>
                </div>
            </div>

            <div class="mainformblock-block-cell">
                <div class="mainformblock-info">
                    <div class="mainformblock-info-item">
                        <div class="mainformblock-info-item__img"><img src="img/maininfoblock/01.png" alt="" /></div>
                        <div class="mainformblock-info-item__text">Скупаем только новые картриджи</div>
                    </div>
                    <div class="mainformblock-info-item">
                        <div class="mainformblock-info-item__img"><img src="img/maininfoblock/02.png" alt="" /></div>
                        <div class="mainformblock-info-item__text">Не покупаем Б/У, восстановленные совместимые картриджи</div>
                    </div>
                    <div class="mainformblock-info-item">
                        <div class="mainformblock-info-item__img"><img src="img/maininfoblock/03.png" alt="" /></div>
                        <div class="mainformblock-info-item__text">Принимаем заявки по всей России. Сотрудничаем с региональными дилерами.</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section('additional-js')
    @if(!empty(Session::get('send')) && Session::get('send'))
        <script>
            ym(38574200,'reachGoal','SENDFORMUSPEHGLAV');
        </script>
    @endif
@stop

site/resources/views/pages/home_components/mainnews_blockbg.blade.php
@if(count($news))
    <div class="mainnews blockbg">
        <div class='container'>
            <div class="mainnews__title title_3">новости</div>
            <div class="mainnews-block">
                @foreach($news as $news_item)
                    <div class="mainnews-item">
                        <div class="mainnews-cell">
                            <div class="mainnews-image">
                                <a href="{{route('newsitem',$news_item->_slug)}}"><img src="{{$news_item->image_url}}" alt="" /></a>
                            </div>
                        </div>
                        <div class="mainnews-cell">
                            <div class="mainnews-body">
                                <a href="{{route('newsitem',$news_item->_slug)}}" class="mainnews-body__title">{{$news_item->title}}</a>
                                <div class="mainnews-body__data">{{$news_item->date}}</div>
                                <div class="mainnews-body__text">{{$news_item->preview}}<a class="mainnews-body__more" href="{{route('newsitem',$news_item->_slug)}}">Читать далее ›</a></div>
                            </div>
                        </div>
                    </div>
                @endforeach

                <div class="mainnews-block-bottom">
                    <a href="{{route('news')}}" class="popup-body__btn"><span>все новости</span></a>
                </div>

            </div>
        </div>
    </div>

@endif

site/resources/views/pages/home_components/mainpopular.blade.php
@if(count($populars))
    <a name="mainpopular"></a>
    <div class="mainpopular">
        <div class='container'>
            <div class="mainpopular__title title_3">популярные предложения</div>
            <div class="mainpopular-row row">
                @foreach($populars as $popular)
                    <div class="mainpopular-column">
                        <div class="mainpopular-item">
                            <div class="mainpopular-item__image">
                                <a href="{{$popular->slug}}"><img src="{{$popular->image_url}}" alt="" /></a>
                            </div>
                            <a href="" style="word-break: break-all;" class="mainpopular-item__title">{{str_limit($popular->title, 16)}}</a>
                            <div class="mainpopular-item__price">{{$popular->price}} руб</div>
                            <a href="{{$popular->slug}}" class="mainpopular-item__btn">продать</a>
                        </div>
                    </div>
                @endforeach
            </div>
        </div>
    </div>
@endif

site/resources/views/pages/home_components/mainruls_blockbg.blade.php
<a name="mainruls"></a>
<div class="mainruls blockbg" >
    <div class='container'>
        <div class="mainruls__title title_3">правила работы</div>
        <div class="mainruls-block row">
            <div class="mainruls-column">
                <div class="mainruls-item">
                    <div class="mainruls-item__icon">1</div>
                    <div class="mainruls-item__text"><strong>Не скупаем</strong> Б/У картриджи. Все картриджи должны быть в заводской упаковке.</div>
                </div>
            </div>
            <div class="mainruls-column">
                <div class="mainruls-item">
                    <div class="mainruls-item__icon">2</div>
                    <div class="mainruls-item__text">Покупаем только оригинальные картриджи. Восстановленные, совместимые подделки - <br /><strong>не скупаем</strong>.</div>
                </div>
            </div>
            <div class="mainruls-column">
                <div class="mainruls-item">
                    <div class="mainruls-item__icon">3</div>
                    <div class="mainruls-item__text"><strong>Срок годности</strong> картриджей: струйные не менее 6 мес., лазерные - не менее 3 лет.</div>
                </div>
            </div>
            <div class="mainruls-column">
                <div class="mainruls-item">
                    <div class="mainruls-item__icon">4</div>
                    <div class="mainruls-item__text">Оплата товара (в т.ч. и отправленного с регионов) производится только после проверки. Весь товар оплачивается по факту. <br /> <strong>Предоплаты нет</strong>.</div>
                </div>
            </div>
        </div>
    </div>
</div>

site/resources/views/pages/home_components/mainsteps.blade.php
<div class="mainsteps">
    <div class='container'>
        <div class="mainsteps__title title_1">4 простых шага нашего<br />сотрудничества</div>
        <div class="mainsteps-row row">
            <div class="mainsteps-column">
                <div class="mainsteps-item">
                    <div class="mainsteps-item__icon"><img src="img/steps/01.png" alt="" /></div>
                    <div class="mainsteps-item__text">Вы оставляете заявку или звоните нам</div>
                </div>
            </div>
            <div class="mainsteps-column">
                <div class="mainsteps-item">
                    <div class="mainsteps-item__icon"><img src="img/steps/02.png" alt="" /></div>
                    <div class="mainsteps-item__text">Согласование условий и встречи</div>
                </div>
            </div>
            <div class="mainsteps-column">
                <div class="mainsteps-item">
                    <div class="mainsteps-item__icon"><img src="img/steps/03.png" alt="" /></div>
                    <div class="mainsteps-item__text">Проверка состояния, фактическая оценка</div>
                </div>
            </div>
            <div class="mainsteps-column">
                <div class="mainsteps-item">
                    <div class="mainsteps-item__icon"><img src="img/steps/04.png" alt="" /></div>
                    <div class="mainsteps-item__text">Оплата наличными или на карту</div>
                </div>
            </div>
        </div>
    </div>
</div>

site/resources/views/pages/home_components/maintext_blockbg.blade.php
@if(count($info_company->main_page_content))
    <div class="maintext blockbg">
        <div class='container'>
            <div class="maintext__title title_3">покупка картриджей для принтеров</div>

            <div class="maintext-block">
                {!! html_entity_decode($info_company->main_page_content) !!}
            </div>
        </div>
    </div>
@endif