site/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
//home
get('/',['as'=>'home','uses'=>'StaticPagesController@indexHome']);
//user pages
get('/pages/{slug}',['as'=>'user_pages','uses'=>'StaticPagesController@indexUserPages']);
//about
get('/about',['as'=>'about','uses'=>'StaticPagesController@indexAbout']);
//working conditions
get('/rules',['as'=>'rules','uses'=>'StaticPagesController@indexRules']);
//contacts
//get('/contacts',['as'=>'contacts','uses'=>'StaticPagesController@indexContacts']);
//regions
get('/regions',['as'=>'regions','uses'=>'StaticPagesController@indexRegions']);

get('/data_exchange',['as'=>'data_exchange','uses'=>'DataExchangeController@dataExchange']);
//dataExchange
get('/load_orders',['as'=>'data_exchange','uses'=>'DataExchangeController@LoadOrders']);



//GetCartridgePrice
get('/price/{slug}/{pagination?}',['as'=>'price_brand','uses'=>'CartridgePriceController@getCartidgePrices']);
//DownloadCartridgePrice
get('/exel/{slug?}',['as'=>'exel_download','uses'=>'CartridgePriceController@downloadPriceExel']);



//request
//get('/request',['as'=>'request','uses'=>'RequestController@index']);
//store request
post('/store_request',['as'=>'store_request','uses'=>'RequestController@store_request']);
//store request call back
post('/call_back',['as'=>'call_back','uses'=>'RequestController@call_back']);


//news
get('/news',['as'=>'news','uses'=>'NewsController@index']);
//newsitem
get('/news/{_news_slug}',['as'=>'newsitem','uses'=>'NewsController@indexNewsItem']);

//


//questions
//get('/questions',['as'=>'questions','uses'=>'QuestionsController@index']);
//store questions
//get('/questions_store',['as'=>'store_questions','uses'=>'QuestionsController@store']);

//cart
get('/cart',['as'=>'cart','uses'=>'CartController@index']);
//cart update
post('/cart_update',['as'=>'cart_add','uses'=>'CartController@cart_update']);
//cart order delete
post('/cart_item_delete',['as'=>'cart_item_delete','uses'=>'CartController@cart_item_delete']);
//clean session orders
get('/clean_cart',['as'=>'clean_cart','uses'=>'CartController@clean_cart']);
//add to orders
post('/cart_item_delete',['as'=>'cart_item_delete','uses'=>'CartController@cart_item_delete']);
//save order
post('/save_order',['as'=>'save_order','uses'=>'CartController@save_order']);


//search
get('/search',['as'=>'search','uses'=>'SearchController@search']);
get('/autocomplete',['as'=>'autocomplete','uses'=>'SearchController@autocomplete']);

Route::group(['prefix'=>'uploader','nocsrf' => true],function(){
    Route::match(['get','post'],'/','Fileuploader@upload');
});

site/app/Models/News.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use SmartModel\SmartModel;

class News extends SmartModel

{
    protected $news_tag_ids = [];
    protected $appends = ['tags_as_string',];

    public $rules = array(
        'title' => 'required',
//        '_slug' => 'required',
    );

    public static $files = array(
        'image' => array(
            'sizes' => array(
                'list' => array(
                    'size' => '161x108',
                    'process' => 'fitOut',
                ),
            ),
        ),
        'image_poster' => array(
            'sizes' => array(
                'poster'=>array(
                    'size' => '408x330',
                    'process' => 'fitOut',
                ),
            ),
        ),
        'og_image' => array(
            'name' => 'native',
        ),
    );

    public  function getTagsAsStringAttribute(){
        $id_news    =   $this->id;
        return (implode(",",\DB::table('tags')
                            ->select('title')
                            ->whereIn('tags.id', \DB::table('tags_to_news')
                                                ->select('id_tag')
                                                ->where('id_news',$id_news)->lists('id_tag'))
                            ->lists('title') ));
    }

    public  function getDateAttribute(){
        return Carbon::parse($this->created_at)->format('d.m.Y');
    }
    
    public  function getImageUrlAttribute(){
        $this->loadFiles();
        if (count($this->image['sizes']['list']['link'])){
            return asset($this->image['sizes']['list']['link']);
        }
        return asset('img/products/01.png');
    }

    public  function getBigImgAttribute(){
        $this->loadFiles();
        if (count($this->image_poster['sizes']['poster']['link'])){
            return asset($this->image_poster['sizes']['poster']['link']);
        }
        return asset('img/image.png');
    }



    public function afterSave() {
        parent::afterSave();
        $id_news = $this->id;
        $id_tags_for_news =  $this->news_tag_ids;
        \DB::table('tags_to_news')->where('id_news',$id_news)->delete();
        $tags_this_news=[];
        foreach($id_tags_for_news as $val){
            $tags_this_news[]=['id_news' =>  $id_news,
                                'id_tag'  =>  $val];
        }
//        dd($tags_this_news);
        \DB::table('tags_to_news')->insert($tags_this_news);

    }

    public  function setTagsAsStringAttribute($val){
        $tags_this_news =  explode(',', $val);
        foreach ($tags_this_news as &$_tag) {
            $_tag = trim($_tag);
        }

        $existing_tags   =    \DB::table('tags')->whereIn('title',$tags_this_news)->lists('title','id');
        $id_existing_tags   =   array_keys($existing_tags);
        $tile_existing_tags =   array_values($existing_tags);
//get tags that still do not have
        $non_existent_tags  =   array_diff( $tags_this_news, $tile_existing_tags);
//form a list of the id record
        $id_tags_for_news  = $id_existing_tags;
//add new tag
        foreach($non_existent_tags as $tag){
            $id_tags_for_news[] = \DB::table('tags')->insertGetId(['title'=>$tag]);
        }
//remove all tags for this news
//        \DB::table('tags_to_news')->where('id_news',$id_news)->delete();

////        $tags_this_news=[];
//        foreach($id_tags_for_news as $val){
//            $tags_this_news[]=['id_news' =>  $id_news,
//                              'id_tag'  =>  $val];
//        }
        $this->news_tag_ids = $id_tags_for_news;
//        write new tags for news

//        \DB::table('tags_to_news')->insert($tags_this_news);
    }

    public static function getNewNews() {
        return \DB::table('news')
            ->where('is_active','=',1)->whereNotNull('_slug')->where('_slug','<>','')
            ->limit(3)->orderBy('created_at','desc')->get();
    }

    public static function getNewsPaginationList($on_page = 10)
    {
        $news = News::where('is_active','=',1)->whereNotNull('_slug')->where('_slug','<>','')
                ->orderBy('created_at','desc')
                ->paginate($on_page);

        return $news;
    }

    public static function getNewsByIds($ids)
    {
        $news = News::where('is_active','=',1)->whereNotNull('_slug')->where('_slug','<>','')
                ->whereIn('id',$ids)
                ->orderBy('created_at','desc')
                ->get();

        return $news;
    }

    public static function getLikeNews($id_news)
    {
        $news_top = \DB::table('tags_to_news')
            ->select(\DB::raw('count(*) as count, id_news'))
            ->join('news', 'id_news', '=', 'news.id')
            ->where('is_active','=',1)->whereNotNull('_slug')->where('_slug','<>','')
            ->whereIn('id_tag',\DB::table('tags_to_news')
                ->where('id_news',$id_news)->lists('id_tag'))
            ->groupBy('id_news')
            ->orderBy('count','desc')
            ->limit(5)->get();

        $news_ids = [];
        foreach ($news_top as $nt) {
            if ($nt->id_news != $id_news) {
                $news_ids[] = $nt->id_news;
            }
        }

        return self::getNewsByIds($news_ids);
//
//        return \DB::table('tags_to_news')
//            ->select(\DB::raw('count(*) as count, id_news, news.title, news.content,news.preview, news.created_at,news.id'))
//            ->join('news', 'id_news', '=', 'news.id')
//            ->where('is_active','=',1)
//            ->whereIn('id_tag',\DB::table('tags_to_news')
//                ->where('id_news',$id_news)->lists('id_tag'))
//            ->groupBy('id_news')
//            ->orderBy('count','desc')
//            ->limit(5)->get();
    }
}

site/resources/views/pages/cart.blade.php
@extends('layouts.default')
@section('content')
    @if(!isset($cart_orders_item))
        @if(isset($send) && $send)
            <div class='container cart_empty_text'>
                <div class="content-breadcrumbs noprint">
                    {!!\App\Http\Controllers\BreadcrumbsController::printBreadCrumbs()!!}
                </div>
                <div class="content__title title_1 title_success">Ваша заявка @if(isset($code)) № {{$code}}  от {{$date}} @endifуспешно отправлена</div>
            </div>
        @else
            <div class='container cart_empty_text'>
                <div class="content-breadcrumbs noprint">
                    {!!\App\Http\Controllers\BreadcrumbsController::printBreadCrumbs()!!}
                </div>
                <div class="content__title title_1">Корзина пуста</div>
            </div>
        @endif

    @else
    <div class="content">
        <div class='container'>
            <div class="content-breadcrumbs noprint">
                {!!\App\Http\Controllers\BreadcrumbsController::printBreadCrumbs()!!}
            </div>
            <div class="content__title title_1 noprint">оформление заявки <br />на продажу картриджей</div>
            <div class="content__title_print">Заявка от {{date("d.m.Y")}}</div>


            <div class="content-filter " >
                @if(isset($count_items))
                    <div class="content-filter-sector " >Выбрано товаров: <strong  id="cart_count">{{$count_items}}</strong> шт.</div>
                    <div class="content-filter-sector "  >На сумму: <strong id="cart_sum">{{$sum_items}}</strong> руб.</div>
                @else
                    <div class="content-filter-sector " >Выбрано товаров: <strong>0 шт.</strong></div>
                    <div class="content-filter-sector " >На сумму: <strong>0 руб.</strong></div>
                @endif
            </div>

            <div class="filter_print_div" >
                @if(isset($count_items))
                    <div class="filter_print" style="margin-right: 8px;" >Выбрано товаров: <strong  id="cart_count">{{$count_items}}</strong> шт.</div>
                    <div class="filter_print "  >На сумму: <strong id="cart_sum">{{$sum_items}}</strong> руб.</div>
                @else
                    <div class="filter_print" style="margin-right: 8px;">Выбрано товаров: <strong>0 шт.</strong></div>
                    <div class="filter_print" >На сумму: <strong>0 руб.</strong></div>
                @endif
            </div>


            <div class="content-table " id="print_table">
                <table>
                    <tr>
                        <th>Артикул</th>
                        <th>модель принтера</th>
                        <th>цена, руб.</th>
                        <th>количество, шт.</th>
                        <th>сумма, руб.</th>
                        <th class="noprint">удалить</th>
                    </tr>
                    @if(isset($cart_orders_item))
                        @foreach($cart_orders_item as $key=>$value)
                            <tr>
                                <td colspan="6">
                                    <div id="type-{{$value['0']->typeId}}" class="content-table__subheader">{{$key}}</div>
                                </td>
                            </tr>
                            @foreach($value as $item)
                                <tr id="tr-{{$item->id}}">
                                    <td >{{$item->articule}}</td>
                                    <td>{{$item->brand}} {{$item->cartridge_model}}</td>
                                    <td class="price_RUB-{{$item->id}}">{{$item->price_RUB}}</td>
                                    <td >
                                        <div class="quantity">
                                            <div class="quantity__btn dwn noprint"  id="{{$item->id}}" onselectstart="return false" onmousedown="return false"></div>
                                            <input type="text" name="form[]"  value="{{$cart_items[$item->id]["count"]}}" id="{{$item->id}}" class="item_{{$item->id}} number quantity__inp " />
                                            <div class="quantity__btn up noprint"  id="{{$item->id}}" onselectstart="return false" onmousedown="return false"></div>
                                        </div>
                                    </td>
                                    <td id="order_{{$item->id}}" sum="{{$item->price_RUB}}">{{$cart_items[$item->id]["count"]*$cart_items[$item->id]["sum"]}}</td>
                                    <td class="noprint"><a class="content-table__dell type-{{$item->typeId}}" data-filter="{{$item->typeId}}" data-href="{{URL::route('cart_item_delete')}}" id="{{$item->id}}"></a></td>
                                </tr>
                            @endforeach
                        @endforeach
                    @endif

                </table>
            </div>
            <div class="content-form noprint">
                <div class="content-form__title title_2">ваши контактные данные<br />для заявки</div>
                <form action="{{route('save_order')}}" enctype="multipart/form-data" method='POST'>
{{--                    <input type="hidden" name="recaptcha_response" id="recaptchaResponse">--}}
                    {{ HiddenCaptcha::render() }}
                    <div class="popup-body-row row" >
                        <div class="popup-body-column ">
                            <input type="text" name="name" data-value="Как к Вам обращаться?" class="popup-body__input" />
                        </div>
                        <div class="popup-body-column ">
                            <input type="text"  name="phone" data-value="Контактный телефон" class="number_phone popup-body__input" />
                        </div>
                        <div class="popup-body-column ">
                            <input type="text" name="email" data-value="Электронная почта" class="popup-body__input req email" />
                        </div>
                        <div class="popup-body-column ">
                            <div class="select content-filter__select">
                                <div class="select-title">
                                    <div class="select-title__arrow"></div>
                                    <div class="select-title__value">Екатеринбург</div>
                                </div>
                                <div class="select-options">
                                    <div class="select-options-inside">
                                        <div class="select-options__value">Екатеринбург</div>
                                        <div class="select-options__value">Свердловская область и Урал</div>
                                        <div class="select-options__value">Другой город</div>
                                    </div>
                                    <input type="hidden" class="req" name="place" value="Екатеринбург">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="popup-body-row">
                        <textarea name="mess" data-value="Комментарии к заявке" class="popup-body__input"></textarea>
                    </div>
                    <div class="popup-body-row row noprint">
                        <div class="popup-body-column">&nbsp;</div>
                        <div class="popup-body-column">&nbsp;</div>
                        <div class="popup-body-column-recaptcha">
                            <div id="g-recaptcha"></div>
                        </div>
                    </div>
                    <div class="popup-body-row row noprint">
                        <div class="popup-body-column">
                            <div class="popup-body__file">
                                <span>Загрузить фотографии</span>
                            </div>
                            <input type="file" name="images[]" multiple class="popup-body__hiddenfile" />
                        </div>
                        <div class="popup-body-column">
                            <button type="button"  data-href="{{URL::route('clean_cart')}}" class="popup-body__clinbtn clin" @if(!env('TEST_SITE', false)) onclick="yaCounter38574200.reachGoal('KORZINAFORMCLEAR')" @endif><span>очистить</span></button>
                        </div>
                        <div class="popup-body-column">
                            <button type="button" id="print_cart" class="popup-body__printbtn"  @if(!env('TEST_SITE', false)) onclick="yaCounter38574200.reachGoal('KORZINAFORMPRINT')" @endif ><span>распечатать заявку</span></button>
                        </div>
                        <div class="popup-body-column noprint">
                            <input type="hidden" data-value="cart_request"  name="type"/>
                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                            <button type="submit" formaction="{{route('save_order')}}" class="popup-body__btn" @if(!env('TEST_SITE', false)) onclick="yaCounter38574200.reachGoal('KORZINAFORMOTPR')" @endif><span>Отправить заявку</span></button>
                        </div>
                    </div>
                    <div class="popup-body-row last noprint">
                        {{--<div class="popup-body-req">--}}
                            {{--<span class="star">*</span> Обязательные поля--}}
                        {{--</div>--}}
                    </div>
                </form>
            </div>
            <div class="print_order_form">
                <p class="print_order_form_text">Ваши контактные данные</p>
                <table id="print_form">
                    <tr>
                        <td class="col1">Имя:</td>
                        <td class="print_name"></td>
                    </tr>
                    <tr>
                        <td class="col1">Контактный телефон:</td>
                        <td  class="print_phone"></td>
                    </tr>
                    <tr>
                        <td class="col1">Электронная почта:</td>
                        <td  class="print_email"></td>
                    </tr>
                    <tr>
                        <td class="col1">Ваш город:</td>
                        <td  class="print_city"></td>
                    </tr>
                    <tr>
                        <td class="col1">Комментарий к заявке</td>
                        <td  class="print_comment"></td>
                    </tr>

                </table>
            </div>

        </div>
    </div>
    <div class="mainsteps mainsteps__inside noprint">
        <div class='container'>
            <div class="mainsteps__title title_3">после отправки заявки</div>
            <div class="mainsteps-row row">
                <div class="mainsteps-column">
                    <div class="mainsteps-item">
                        <div class="mainsteps-item__icon"><img src="img/steps/01.png" alt="" /></div>
                        <div class="mainsteps-item__text">Вы оставляете заявку или звоните нам</div>
                    </div>
                </div>
                <div class="mainsteps-column">
                    <div class="mainsteps-item">
                        <div class="mainsteps-item__icon"><img src="img/steps/02.png" alt="" /></div>
                        <div class="mainsteps-item__text">Согласование условий и встречи</div>
                    </div>
                </div>
                <div class="mainsteps-column">
                    <div class="mainsteps-item">
                        <div class="mainsteps-item__icon"><img src="img/steps/03.png" alt="" /></div>
                        <div class="mainsteps-item__text">Проверка состояния, фактическая оценка</div>
                    </div>
                </div>
                <div class="mainsteps-column">
                    <div class="mainsteps-item">
                        <div class="mainsteps-item__icon"><img src="img/steps/04.png" alt="" /></div>
                        <div class="mainsteps-item__text">Оплата наличными или на карту</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @endif
@stop

@section('additional-js')
    @if(!isset($cart_orders_item))
        @if(isset($send) && $send)
            <script>
                ym(38574200,'reachGoal','SENDFORMUSPEHKORZINA');
            </script>
        @endif
    @endif
@stop

site/resources/views/pages/cartridge_price.blade.php
@extends('layouts.default')
@section('content')
    <div class="content">
        <div class='container'>
            <div class="content-breadcrumbs">
                {!!\App\Http\Controllers\BreadcrumbsController::printBreadCrumbs()!!}
            </div>
            <div class="content__title title_3">скупка картриджей {{$cartridge_brand->title}}</div>
            {{--<div class="content-text">--}}
                {{--<p>Внимание покупателям! Наша компания осуществляет покупку только новых картриджей НР (не Б/У). Конечная стоимость зависит от состояния упаковки, срока годности, количества.</p>--}}
            {{--</div>--}}
            <div class="content-filter">
                <div class="content-filter-sector" style=" width: 190px;"></div>
                <div class="content-filter-sector">Отображать на странице: <a href="{{route('price_brand',['slug'=>$cartridge_brand->_slug,'pagination'=>10])}}" class="content-filter__control">10</a> <a href="{{route('price_brand',['slug'=>$cartridge_brand->_slug,'pagination'=>50])}}" class="content-filter__control">50</a> <a href="{{route('price_brand',['slug'=>$cartridge_brand->_slug])}}" class="content-filter__control active">Все</a></div>
                <div class="content-filter-sector"><a href="{{URL::route('exel_download',$cartridge_brand->_slug)}}" class="content__pricedwn" @if(!env('TEST_SITE', false)) onclick="yaCounter38574200.reachGoal('DOWNLOADPRICE')" @endif><span>Скачать прайс-лист {{$cartridge_brand->title}}</span></a></div>
            </div>
            <ul class="price-shortlinks">
                <!--noindex-->
                @if(!empty($cartridge_price_item) && count($cartridge_price_item)>1)
                    @foreach(array_keys($cartridge_price_item) as $i=>$key)
                        <li>
                            <a class="price-shortlink" href="#type-{{$i+1}}" rel="nofollow">{{$key}}</a>
                        </li>
                    @endforeach
                <!--/noindex-->
                @endif
            </ul>
            <div class="content-table">
                <table>
                    <tr>
                        <th>Артикул</th>
                        <th>модель принтера</th>
                        <th>цена, руб.</th>
                        <th>количество, шт.</th>
                        <th>сумма, руб.</th>
                        {{--<th>в корзину</th>--}}
                    </tr>
                    @if(!empty($cartridge_price_item))
                        <?php $i = 1; ?>
                        @foreach($cartridge_price_item as $key=>$value)
                            <tr>
                                <td colspan="6">
                                    <div class="content-table__subheader" id="type-{{$i++}}">{{$key}}</div>
                                </td>
                            </tr>
                            @foreach($value as $item)
                                <tr>
                                    <td>{{$item->articule}}</td>
                                    <td class="model">
                                        <div>
                                            {{$item->cartridge_model}}
                                        </div>
                                    </td>
                                    <td class="price_RUB-{{$item->id}}">{{$item->price_RUB}}</td>
                                    <td>
                                        <div class="quantity">
                                            <div class="quantity__btn dwn" id="{{$item->id}}" onselectstart="return false" onmousedown="return false"></div>
                                            @if(isset($cart_items[$item->id]))
                                                <input type="text" name="form[]" value="{{$cart_items[$item->id]["count"]}}" id="{{$item->id}}" class="number quantity__inp item_{{$item->id}}" />
                                            @else
                                                <input type="text" name="form[]" value="0" id="{{$item->id}}" class="number quantity__inp item_{{$item->id}}" />
                                            @endif
                                            <div class="quantity__btn up" id="{{$item->id}}" onselectstart="return false" onmousedown="return false" ></div>
                                        </div>
                                    </td>
                                    @if(isset($cart_items[$item->id]))
                                        <td id="order_{{$item->id}}" sum="{{$item->price_RUB}}">{{$cart_items[$item->id]["count"]*$cart_items[$item->id]["sum"]}}</td>
                                    @else
                                        <td id="order_{{$item->id}}" sum="{{$item->price_RUB}}">{{$item->price_RUB}}</td>
                                    @endif
                                    {{--<td><a class="content-table__add">Добавить в корзину</a></td>--}}
                                    <input type="hidden" value="{{$item->id}}" name="id">
                                    <input type="hidden" value="{{$item->price_RUB}}" name="price_RUB">
                                </tr>
                            @endforeach
                        @endforeach
                    @endif
                </table>
            </div>

            @include('components.pagination',['paginator' => $paginate_list])

        </div>
    </div>
    <div class="maintext blockbg">
        <div class='container'>
            <div class="maintext__title title_3">прайс-лист {{$cartridge_brand->title}}</div>
            <div class="maintext-block">
                @if(count($cartridge_brand->bottom_text_for_brands))
                    {!!$cartridge_brand->bottom_text_for_brands!!}
                @endif
            </div>
        </div>
    </div>
    <script>
            if($('.header-cart').length){
                var objToStick = $(".header-cart"); //Получаем нужный объект
                var topOfObjToStick = $(objToStick).offset().top; //Получаем начальное расположение нашего блока
                console.log(window.innerWidth);
                $(window).scroll(function () {
                    var windowScroll = $(window).scrollTop(); //Получаем величину, показывающую на сколько прокручено окно
                    if (windowScroll > topOfObjToStick+40) { // Если прокрутили больше, чем расстояние до блока, то приклеиваем его
                        $(objToStick).addClass("topWindow");
                        var right_margin = 260;
                        if(window.innerWidth < 1600){
                            right_margin = 0;
                        }
                        $('.topWindow').css("right", right_margin);
                    } else {
                        $(objToStick).removeClass("topWindow");
                    };
                });

            }
    </script>
@stop

site/resources/views/pages/home.blade.php
@extends('layouts.default')

@section('content')

    @include('pages.home_components.mainsteps')

    @include('pages.home_components.mainformblock')

    @include('pages.home_components.mainruls_blockbg')

    @include('pages.home_components.mainpopular')

    @include('pages.home_components.mainnews_blockbg')

    @include('pages.home_components.mainbrands')

    @include('pages.home_components.maintext_blockbg')

@stop

site/resources/views/pages/news.blade.php
@extends('layouts.default')
@section('content')
    <div class="content">
        <div class='container'>
            <div class="content-breadcrumbs">
                {!!\App\Http\Controllers\BreadcrumbsController::printBreadCrumbs()!!}
            </div>
            <div class="content__title title_3">Новости</div>
            <div class="content-news">
                @if(count($news))
                    @foreach($news as $news_item)
                        <div class="mainnews-item">
                            <div class="mainnews-cell">
                                <div class="mainnews-image">
                                    <a href="{{route('newsitem',$news_item->_slug)}}"><img src="{{$news_item->image_url}}" alt="" /></a>
                                </div>
                            </div>
                            <div class="mainnews-cell">
                                <div class="mainnews-body">
                                    <a href="{{route('newsitem',$news_item->_slug)}}" class="mainnews-body__title">{{$news_item->title}}</a>
                                    <div class="mainnews-body__data">{{$news_item->date}}</div>
                                    <div class="mainnews-body__text">{{$news_item->preview}}<a class="mainnews-body__more" href="{{route('newsitem',$news_item->_slug)}}">Читать далее ›</a></div>
                                </div>
                            </div>
                        </div>
                    @endforeach
                @endif
            </div>

            @include('components.pagination',['paginator' => $news])

        </div>
    </div>
@stop

site/resources/views/pages/newsitem.blade.php
@extends('layouts.default')
@section('content')
    <div class="content">
        <div class='container'>
            <div class="content-breadcrumbs">
                {!!\App\Http\Controllers\BreadcrumbsController::printBreadCrumbs()!!}
            </div>
            <div class="content__title title_3">{!!$news->title!!}</div>
            <div class="content-news">
                <div class="content-news__image">
                    <a class="zoom" href="{{$news->big_img}}"><img src="{{$news->big_img}}" alt="{{$news->title}}" /></a>
                </div>
                <span class="mainnews-body__data">{{$news->date}}</span>
					<span class="mainnews-body__text">
						{!!$news->content!!}
					</span>
            </div>
        </div>
    </div>
@stop